<?php
return array(
    array(
        'pagetitle' => 'Sample Store',
        'longtitle' => 'Sample Store',
        'menutitle' => 'Sample Store',
        'description' => 'An example store',
        'alias' => 'sample-store',
        'uri' => 'sample-store/',
        'class_key' => 'Store',
        'isfolder' => 1,
        'published' => 1,
         'properties' => '{"moxycart":{"product_type":"regular","product_template":"2","sort_order":"SKU","qty_alert":"5","track_inventory":0,"specs":{"1":true,"3":true},"variations":[],"taxonomies":[]}}',
        'Template' => array('templatename' => 'Sample Store'),
        'Products' => array(
            array(
                'name' => 'Moustache Hoodie',
                'title' => 'Moustache Hoodie',
                'description' => 'Our handsome hoodie for hirsute homeys',
                'content' => '<p>Just imagine this awesome product.</p>',
                'type' => 'regular',
                'sku' => 'MOUSTACHE-HOODIE',
                'sku_vendor' => '',
                'alias' => 'moustache-hoodie',
                'uri' => 'sample-store/moustache-hoodie',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '19.00',
                'price_strike_thru' => '25.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Shaved Sweater',
                'title' => 'Shaved Sweater',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'SHAVED-SWEATER',
                'sku_vendor' => '',
                'alias' => 'shaved-sweater',
                'uri' => 'sample-store/shaved-sweater',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '79.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Another Sweater',
                'title' => 'Another Sweatersss',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'ANOTHER-SWEATER',
                'sku_vendor' => '',
                'alias' => 'another-sweater',
                'uri' => 'sample-store/another-sweater',
                'track_inventory' => 0,
                'in_menu' => 1,
                'is_active' => 1,
                'qty_inventory' => 78,
                'qty_alert' => 4,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Yet Another Sweater',
                'title' => 'Yet Another Sweater',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'YET-ANOTHER-SWEATER',
                'sku_vendor' => '',
                'alias' => 'yet-another-sweater',
                'uri' => 'sample-store/yet-another-sweater',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Plain White Tee',
                'title' => 'Plain White Tee',
                'description' => '100% Cotton Plain White Shirt',
                'content' => '<p>Just imagine this awesome Shirt.</p>',
                'type' => 'regular',
                'sku' => 'PLAIN-WHITE-TEE',
                'sku_vendor' => '',
                'alias' => 'plain-white-tee',
                'uri' => 'sample-store/yet-another-sweater',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '50.00',
                'price_strike_thru' => '82.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Red Cool Tee',
                'title' => 'Red Cool Tee',
                'description' => '100% Cotton Colored Shirt',
                'content' => '<p>Just imagine this awesome Shirt.</p>',
                'type' => 'regular',
                'sku' => 'RED-COOL-TEE',
                'sku_vendor' => '',
                'alias' => 'red-cool-tee',
                'uri' => 'sample-store/red-cool-tee',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '55.00',
                'price_strike_thru' => '90.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Blue Cool Tee',
                'title' => 'Blue Cool Tee',
                'description' => '100% Cotton Colored Shirt',
                'content' => '<p>Just imagine this awesome Shirt.</p>',
                'type' => 'regular',
                'sku' => 'BLUE-COOL-TEE',
                'sku_vendor' => '',
                'alias' => 'blue-cool-tee',
                'uri' => 'sample-store/blue-cool-tee',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '55.00',
                'price_strike_thru' => '90.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Purple Cool Tee',
                'title' => 'Purple Cool Tee',
                'description' => '100% Cotton Colored Shirt',
                'content' => '<p>Just imagine this awesome Shirt.</p>',
                'type' => 'regular',
                'sku' => 'PURPLE-COOL-TEE',
                'sku_vendor' => '',
                'alias' => 'purple-cool-tee',
                'uri' => 'sample-store/purple-cool-tee',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '55.00',
                'price_strike_thru' => '90.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'White Black Stripe Tee',
                'title' => 'White Black Stripe Tee',
                'description' => '100% Cotton Stripe Shirt',
                'content' => '<p>Just imagine this awesome Stripe Shirt.</p>',
                'type' => 'regular',
                'sku' => 'WHITE-BLACK-STRIPE',
                'sku_vendor' => '',
                'alias' => 'white-black-stripe-tee',
                'uri' => 'sample-store/white-black-stripe-tee',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '72.00',
                'price_strike_thru' => '93.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Red Black Stripe Tee',
                'title' => 'Red Black Stripe Tee',
                'description' => '100% Cotton Stripe Shirt',
                'content' => '<p>Just imagine this awesome Stripe Shirt.</p>',
                'type' => 'regular',
                'sku' => 'RED-BLACK-STRIPE',
                'sku_vendor' => '',
                'alias' => 'red-black-stripe-tee',
                'uri' => 'sample-store/red-black-stripe-tee',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '72.00',
                'price_strike_thru' => '93.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'White Plain Polo Shirt',
                'title' => 'White Plain Polo Shirt',
                'description' => '100% Cotton Polo Shirt',
                'content' => '<p>Just imagine this awesome Polo Shirt.</p>',
                'type' => 'regular',
                'sku' => 'WHITE-PLAIN-POLO-SHIRT',
                'sku_vendor' => '',
                'alias' => 'white-plain-polo-shirt',
                'uri' => 'sample-store/white-plain-polo-shirt',
                'track_inventory' => 1,
                'qty_inventory' => 2,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '78.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Black Plain Polo Shirt',
                'title' => 'Black Plain Polo Shirt',
                'description' => '100% Cotton Polo Shirt',
                'content' => '<p>Just imagine this awesome Polo Shirt.</p>',
                'type' => 'regular',
                'sku' => 'BLACK-PLAIN-POLO-SHIRT',
                'sku_vendor' => '',
                'alias' => 'black-plain-polo-shirt',
                'uri' => 'sample-store/black-plain-polo-shirt',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '78.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'White Sleeveless Undershirt',
                'title' => 'White Sleeveless Undershirt',
                'description' => '100% Cotton Sleeveless Undershirt',
                'content' => '<p>Just imagine this awesome Sleeveless Undershirt.</p>',
                'type' => 'regular',
                'sku' => 'WHITE-SLEEVELESS-UNDERSHIRT',
                'sku_vendor' => '',
                'alias' => 'white-sleeveless-undershirt',
                'uri' => 'sample-store/white-sleeveless-undershirt',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '48.00',
                'price_strike_thru' => '60.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Black Sleeveless Undershirt',
                'title' => 'Black Sleeveless Undershirt',
                'description' => '100% Cotton Sleeveless Undershirt',
                'content' => '<p>Just imagine this awesome Sleeveless Undershirt.</p>',
                'type' => 'regular',
                'sku' => 'BLACK-SLEEVELESS-UNDERSHIRT',
                'sku_vendor' => '',
                'alias' => 'black-sleeveless-undershirt',
                'uri' => 'sample-store/black-sleeveless-undershirt',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '48.00',
                'price_strike_thru' => '60.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Red Black White Trucker Cap',
                'title' => 'Red Black White Trucker Cap',
                'description' => 'Awesome Net Trucker Cap',
                'content' => '<p>Just imagine this awesome Trucker Cap.</p>',
                'type' => 'regular',
                'sku' => 'RED-BLACK-WHITE-TRUCKER-CAP',
                'sku_vendor' => '',
                'alias' => 'red-black-white-trucker-cap',
                'uri' => 'sample-store/red-black-white-trucker-cap',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '48.00',
                'price_strike_thru' => '60.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Orange Black White Trucker Cap',
                'title' => 'Orange Black White Trucker Cap',
                'description' => 'Awesome Net Trucker Cap',
                'content' => '<p>Just imagine this awesome Trucker Cap.</p>',
                'type' => 'regular',
                'sku' => 'ORANGE-BLACK-WHITE-TRUCKER-CAP',
                'sku_vendor' => '',
                'alias' => 'orange-black-white-trucker-cap',
                'uri' => 'sample-store/orange-black-white-trucker-cap',
                'track_inventory' => 0,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '48.00',
                'price_strike_thru' => '60.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Blue Black White Trucker Cap',
                'title' => 'Blue Black White Trucker Cap',
                'description' => 'Awesome Net Trucker Cap',
                'content' => '<p>Just imagine this awesome Trucker Cap.</p>',
                'type' => 'regular',
                'sku' => 'BLUE-BLACK-WHITE-TRUCKER-CAP',
                'sku_vendor' => '',
                'alias' => 'blue-black-white-trucker-cap',
                'uri' => 'sample-store/blue-black-white-trucker-cap',
                'track_inventory' => 1,
                'qty_inventory' => 1,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '48.00',
                'price_strike_thru' => '60.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Black Slack Pants',
                'title' => 'Black Slack Pants',
                'description' => 'Smooth Slack Pants',
                'content' => '<p>Just imagine this Smooth Slack Pants.</p>',
                'type' => 'regular',
                'sku' => 'BLACK-SLACK-PANTS',
                'sku_vendor' => '',
                'alias' => 'black-slack-pants',
                'uri' => 'sample-store/black-slack-pants',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '97.00',
                'price_strike_thru' => '110.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Slim Fit Jeans',
                'title' => 'Slim Fit Jeans',
                'description' => 'Slim Fit Jeans',
                'content' => '<p>Just imagine this Slim Fit Jeans.</p>',
                'type' => 'regular',
                'sku' => 'SLIM-FIT-JEANS',
                'sku_vendor' => '',
                'alias' => 'slim-fit-jeans',
                'uri' => 'sample-store/slim-fit-jeans',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '97.00',
                'price_strike_thru' => '110.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Black Boxer Short',
                'title' => 'Black Boxer Short',
                'description' => 'Black Boxer Short',
                'content' => '<p>Just imagine this Cool Boxer Short.</p>',
                'type' => 'regular',
                'sku' => 'BLACK-BOXER-SHORT',
                'sku_vendor' => '',
                'alias' => 'black-boxer-short',
                'uri' => 'sample-store/black-boxer-short',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '41.00',
                'price_strike_thru' => '50.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'White Boxer Short',
                'title' => 'White Boxer Short',
                'description' => 'White Boxer Short',
                'content' => '<p>Just imagine this Cool Boxer Short.</p>',
                'type' => 'regular',
                'sku' => 'WHITE-BOXER-SHORT',
                'sku_vendor' => '',
                'alias' => 'white-boxer-short',
                'uri' => 'sample-store/white-boxer-short',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '41.00',
                'price_strike_thru' => '50.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
            array(
                'name' => 'Dotted Boxer Short',
                'title' => 'Dotted Boxer Short',
                'description' => 'White Boxer Short',
                'content' => '<p>Just imagine this Cool Boxer Short.</p>',
                'type' => 'regular',
                'sku' => 'DOTTED-BOXER-SHORT',
                'sku_vendor' => '',
                'alias' => 'dotted-boxer-short',
                'uri' => 'sample-store/dotted-boxer-short',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '41.00',
                'price_strike_thru' => '50.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 0,
                'in_menu' => 0,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'currency_id' => 109,
                'Template' => array('templatename' => 'Sample Product'),
            ),
        ),  
    ),
    
);
/*EOF*/