<?php
return array(
    array(
        'pagetitle' => 'Sample Store',
        'longtitle' => 'Sample Store',
        'menutitle' => 'Sample Store',
        'description' => 'An example store',
        'alias' => 'sample-store',
        'uri' => 'sample-store/',
        'class_key' => 'Store',
        'isfolder' => 1,
        'published' => 1,
        'Products' => array(
            array(
                'name' => 'Moustache Hoodie',
                'title' => 'Moustache Hoodie',
                'description' => 'Our handsome hoodie for hirsute homeys',
                'content' => '<p>Just imagine this awesome product.</p>',
                'type' => 'regular',
                'sku' => 'MOUSTACHE-HOODIE',
                'sku_vendor' => '',
                'alias' => 'moustache-hoodie',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '19.00',
                'price_strike_thru' => '25.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s')
            ),
            array(
                'name' => 'Shaved Sweater',
                'title' => 'Shaved Sweater',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'SHAVED-SWEATER',
                'sku_vendor' => '',
                'alias' => 'shaved-sweater',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '79.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s')
            ),
            array(
                'name' => 'Another Sweater',
                'title' => 'Another Sweatersss',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'ANOTHER-SWEATER',
                'sku_vendor' => '',
                'alias' => 'another-sweater',
                'track_inventory' => 1,
                'in_menu' => 0,
                'is_active' => 0,
                'qty_inventory' => 78,
                'qty_alert' => 4,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s')
            ),
            array(
                'name' => 'Yet Another Sweater',
                'title' => 'Yet Another Sweater',
                'description' => '100% Wool for hairless homeboys',
                'content' => '<p>Just imagine this awesome sweater.</p>',
                'type' => 'regular',
                'sku' => 'YET-ANOTHER-SWEATER',
                'sku_vendor' => '',
                'alias' => 'yet-another-sweater',
                'track_inventory' => 1,
                'qty_inventory' => 10,
                'qty_alert' => 3,
                'qty_min' => 1,
                'qty_max' => 0,
                'qty_backorder_max' => 5,
                'price' => '49.00',
                'price_strike_thru' => '99.00',
                'price_sale' => '',
                'sale_start' => '',
                'sale_end' => '',
                'category' => 'Default',
                'is_active' => 1,
                'in_menu' => 1,
                'timestamp_created' => date('Y-m-d H:i:s'),
                'Specs' => array(
                    array(
                        'value' => 32,
                        'Spec' => array('identifier'=>'length')
                    ),
                    // There's a bug somewhere here... I can only add 1 Spec...
                    array(
                        'value' => 12,
                        'Spec' => array('identifier'=>'weight')
                    ),
                    
                ),
            ),

        ),  
    ),
);
/*EOF*/