<?php
/**
 * Sends JSON responses.
 * These methods are requested via Ajax requests from pages generated by the PageController.
 * See the IndexManagerController class (index.class.php) for routing info.
 * TODO
 * @package moxycart 
 */
namespace Moxycart;
class ReviewController extends APIController {

    public $model = 'Review';
        
}
/*EOF*/