<?php

 /*               DO NOT EDIT THIS FILE

  Edit the file in the MyComponent config directory
  and run ExportObjects

 */



$packageNameLower = 'moxycart'; 

$components = array(
    /* These are used to define the package and set values for placeholders */
    'packageName' => 'moxycart',  /* No spaces, no dashes */
    'packageNameLower' => $packageNameLower,
    'packageDescription' => 'Foxycart integration for MODX Revolution.',
    'version' => '1.0.0',
    'release' => 'beta1',
    'author' => 'Everett Griffiths',
    'email' => 'everett@craftsmancoding.com',
    'authorUrl' => 'http://craftsmancoding.com/plugins/moxycart',
    'authorSiteName' => "Craftsman Coding",
    'packageDocumentationUrl' => 'https://github.com/craftsmancoding/moxycart/wiki',
    'copyright' => '2013',

    // no need to edit this except to change format
    'createdon' => strftime('%m-%d-%Y'),

    'gitHubUsername' => 'craftsmancoding',
    'gitHubRepository' => 'moxycart',

    // two-letter code of your primary language
    'primaryLanguage' => 'en',

    /* Set directory and file permissions for project directories */
    'dirPermission' => 0755,  /* No quotes!! */
    'filePermission' => 0644, /* No quotes!! */

    /* Define source and target directories (mycomponent root and core directories) */
    'mycomponentRoot' => $this->modx->getOption('mc.root', null,
        MODX_CORE_PATH . 'components/mycomponent/'),
    /* path to MyComponent source files */
    'mycomponentCore' => $this->modx->getOption('mc.core_path', null,
        MODX_CORE_PATH . 'components/mycomponent/core/components/mycomponent/'),
    /* path to new project root */
    'targetRoot' => MODX_ASSETS_PATH . 'mycomponents/' . $packageNameLower . '/',


    /* *********************** NEW SYSTEM SETTINGS ************************ */

    /* If your extra needs new System Settings, set their field values here.
     * You can also create or edit them in the Manager (System -> System Settings),
     * and export them with exportObjects. If you do that, be sure to set
     * their namespace to the lowercase package name of your extra */

    'newSystemSettings' => array(
        'moxycart_system_setting1' => array( // key
            'key' => 'moxycart.foxycart_store_subdomain',
            'name' => 'Foxycart Store Subdomain',
            'description' => 'The URL subdomain for your Foxycart store.',
            'namespace' => 'moxycart',
            'xtype' => 'textfield',
            'value' => '',
            'area' => 'api',
        )
    ),

    /* ************************ NAMESPACE(S) ************************* */
    /* (optional) Typically, there's only one namespace which is set
     * to the $packageNameLower value. Paths should end in a slash
    */

    'namespaces' => array(
        'moxycart' => array(
            'name' => 'moxycart',
            'path' => '{core_path}components/moxycart/',
            'assets_path' => '{assets_path}components/moxycart/',
        ),

    ),



    /* ************************* CATEGORIES *************************** */
    /* (optional) List of categories. This is only necessary if you
     * need to categories other than the one named for packageName
     * or want to nest categories.
    */

    'categories' => array(
        'moxycart' => array(
            'category' => 'Moxycart',
            'parent' => '',  /* top level category */
        ),
    ),

    /* *************************** MENUS ****************************** */

    /* If your extra needs Menus, you can create them here
     * or create them in the Manager, and export them with exportObjects.
     * Be sure to set their namespace to the lowercase package name
     * of your extra.
     *
     * Every menu should have exactly one action */

    'menus' => array(
        'moxycart' => array(
            'text' => 'moxycart',
            'parent' => 'components',
            'description' => 'menu_desc',
            'icon' => '',
            'menuindex' => 0,
            'params' => '',
            'handler' => '',
            'permissions' => '',

            'action' => array(
                'id' => '',
                'namespace' => 'moxycart',
                'controller' => 'index',
                'haslayout' => true,
                'lang_topics' => 'moxycart:default',
                'assets' => '',
            ),
        ),
    ),


    /* ************************* ELEMENTS **************************** */

    /* Array containing elements for your extra. 'category' is required
       for each element, all other fields are optional.
       Property Sets (if any) must come first!

       The standard file names are in this form:
           SnippetName.snippet.php
           PluginName.plugin.php
           ChunkName.chunk.html
           TemplateName.template.html

       If your file names are not standard, add this field:
          'filename' => 'actualFileName',
    */


    'elements' => array(

/*
        'propertySets' => array(
            'PropertySet1' => array(
                'name' => 'PropertySet1',
                'description' => 'Description for PropertySet1',
                'category' => 'moxycart',
            ),
            'PropertySet2' => array(
                'name' => 'PropertySet2',
                'description' => 'Description for PropertySet2',
                'category' => 'moxycart',
            ),
        ),
*/

        'snippets' => array(
            'getProducts' => array(
                'category' => 'Moxycart',
                'description' => 'Returns a list of products.',
                'static' => true,
            ),

            'getRelatedProducts' => array( /* moxycart with static and property set(s)  */
                'category' => 'Moxycart',
                'description' => 'Shows products related to the given product.',
                'static' => false,
/*
                'propertySets' => array(
                    'PropertySet1',
                    'PropertySet2'
                ),
*/
            ),

        ),
        'plugins' => array(
            'MoxyCart' => array( /* moxycart with static, events, and property sets */
                'category' => 'Moxycart',
                'description' => "Swiss Army Knife for all of MoxyCart's needs",
                'static' => false,
/*
                'propertySets' => array(
                    'PropertySet1',
                ),
*/
                'events' => array(
                    'OnPageNotFound' => array(),
                ),
            ),
        ),
        'chunks' => array(
            'tplProduct' => array(
                'description' => 'Used to format product listings.',
                'category' => 'moxycart',
                'static' => true,
            ),
        ),
        'templates' => array(
            'Default Product Template' => array(
                'category' => 'moxycart',
            ),
            'Default Product Template' => array(
                'category' => 'moxycart',
                'description' => 'Demonstrates sample product formatting.',
                'static' => true,
            ),
        ),
/*
        'templateVars' => array(
            'Tv1' => array(
                'category' => 'moxycart',
                'description' => 'Description for TV one',
                'caption' => 'TV One',
                'propertySets' => array(
                    'PropertySet1',
                    'PropertySet2',
                ),
                'templates' => array(
                    'default' => 1,
                    'Template1' => 4,
                    'Template2' => 4,


                ),
            ),
            'Tv2' => array( // moxycart with templates, default, and static specified
                'category' => 'moxycart',
                'description' => 'Description for TV two',
                'caption' => 'TV Two',
                'static' => false,
                'default_text' => '@INHERIT',
                'templates' => array(
                    'default' => 3, // second value is rank -- for ordering TVs when editing resource
                    'Template1' => 4,
                    'Template2' => 1,
                ),
            ),
        ),
*/
    ),
    /* (optional) will make all element objects static - 'static' field above will be ignored */
    'allStatic' => false,



    /* Array of languages for which you will have language files,
     *  and comma-separated list of topics
     *  ('.inc.php' will be added as a suffix). */
    'languages' => array(
        'en' => array(
            'default',
//            'properties',
//            'forms',
        ),
    ),
    /* ********************************************* */
    /* Define optional directories to create under assets.
     * Add your own as needed.
     * Set to true to create directory.
     * Set to hasAssets = false to skip.
     * Empty js and/or css files will be created.
     */
    'hasAssets' => true,
    'minifyJS' => true,
    /* minify any JS files */
    'assetsDirs' => array(
        'css' => true,
        /* If true, a default (empty) CSS file will be created */
        'js' => true,
        /* If true, a default (empty) JS file will be created */
        'images' => true,
        //'audio' => true,
        //'video' => true,
        //'themes' => true,
    ),


    /* ********************************************* */
    /* Define basic directories and files to be created in project*/

    'docs' => array(
        'readme.txt',
        'license.txt',
        'changelog.txt',
    ),

    /* (optional) Description file for GitHub project home page */
    'readme.md' => true,
    /* assume every package has a core directory */
    'hasCore' => true,

    /* ********************************************* */
    /* (optional) Array of extra script resolver(s) to be run
     * during install. Note that resolvers to connect plugins to events,
     * property sets to elements, resources to templates, and TVs to
     * templates will be created automatically -- *don't* list those here!
     *
     * 'default' creates a default resolver named after the package.
     * (other resolvers may be created above for TVs and plugins).
     * Suffix 'resolver.php' will be added automatically */
    'resolvers' => array(
        'default',
    ),

    /* (optional) Validators can abort the install after checking
     * conditions. Array of validator names (no
     * prefix of suffix) or '' 'default' creates a default resolver
     *  named after the package suffix 'validator.php' will be added */

    'validators' => array(
        'default',
    ),

    /* (optional) install.options is needed if you will interact
     * with user during the install.
     * See the user.input.php file for more information.
     * Set this to 'install.options' or ''
     * The file will be created as _build/install.options/user.input.php
     * Don't change the filename or directory name. */
    'install.options' => 'install.options',


    /* Suffixes to use for resource and element code files (not implemented)  */
    'suffixes' => array(
        'modPlugin' => '.php',
        'modSnippet' => '.php',
        'modChunk' => '.html',
        'modTemplate' => '.html',
        'modResource' => '.html',
    ),


    /* ********************************************* */
    /* (optional) Only necessary if you will have class files.
     *
     * Array of class files to be created.
     *
     * Format is:
     *
     * 'ClassName' => 'directory:filename',
     *
     * or
     *
     *  'ClassName' => 'filename',
     *
     * ('.class.php' will be appended automatically)
     *
     *  Class file will be created as:
     * yourcomponent/core/components/yourcomponent/model/[directory/]{filename}.class.php
     *
     * Set to array() if there are no classes. */
    'classes' => array(
        'moxycart' => 'moxycart:moxycart',
    ),

    /* *******************************************
     * These settings control exportObjects.php  *
     ******************************************* */
    /* ExportObjects will update existing files. If you set dryRun
       to '1', ExportObjects will report what it would have done
       without changing anything. Note: On some platforms,
       dryRun is *very* slow  */

    'dryRun' => '0',

    /* Array of elements to export. All elements set below will be handled.
     *
     * To export resources, be sure to list pagetitles and/or IDs of parents
     * of desired resources
    */
    'process' => array(
        'contexts',
        'snippets',
        'plugins',
        'templateVars',
        'templates',
        'chunks',
        'resources',
        'propertySets',
        'systemSettings',
        'contextSettings',
        'systemEvents',
        'menus'
    ),
    /*  Array  of resources to process. You can specify specific resources
        or parent (container) resources, or both.

        They can be specified by pagetitle or ID, but you must use the same method
        for all settings and specify it here. Important: use IDs if you have
        duplicate pagetitles */
//    'getResourcesById' => false,

//    'exportResources' => array(
//        'Resource1',
//        'Resource2',
//    ),
    /* Array of resource parent IDs to get children of. */
//    'parents' => array(),
    /* Also export the listed parent resources
      (set to false to include just the children) */
//    'includeParents' => false,


     /* Array of aliases used in code for the properties array.
     * Used by the checkproperties utility to check properties in code against
     * the properties in your properties transport files.
     * if you use something else, add it here (OK to remove ones you never use.
     * Search also checks with '$this->' prefix -- no need to add it here. */
    'scriptPropertiesAliases' => array(
        'props',
        'sp',
        'config',
        'scriptProperties'
        ),
);

return $components;
